# Fonts
font_family FiraCode
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13.0

# Colors
foreground #aaaaaa
background #000000

map shift+enter send_text all \x1b[13;2u

map alt+space kitten /home/james/devel/flux-kitten/dictation.py
