#!/bin/sh

# Colors
bspc config normal_border_color   "#303030" # unfocused border
bspc config active_border_color   "#707070" # other monitor focused
bspc config focused_border_color  "#1a7cd5" # current monitor focused
bspc config presel_feedback_color "#f4d775"

# Borders
bspc config border_width         2
bspc config window_gap           0

# Layouts
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

# Workspaces
bspc monitor -d 1 2 3 4 5
